[package]
name = "dev_tfhe_rs_nif"
version = "0.1.0"
edition = "2021"

[lib]
name = "dev_tfhe_rs_nif"
crate-type = ["dylib"]
path = "src/lib.rs"

[dependencies]
rustler = "0.29.1"
tfhe = { version = "1.1.3", features = ["boolean", "shortint", "integer", "strings"] }
base64 = "0.21.0"
